### ISSUE TITLE
Having trouble building on macOS

### ISSUE THREAD

**Issue by corbinu** [darfink/jsrt-rs#15]
Having some trouble build on macOS 10.12

I followed the brew install instructions and force linked but perhaps I am just missing something simple

```
chakracore-sys-2d117dd71bab5fd5/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=CHAKRA_SOURCE
cargo:rerun-if-env-changed=CHAKRA_BUILD
/usr/local/bin/pkg-config
chakracore-sys/build.rs:51: Using default ChakraCore build (version: 1.5.1)
chakracore-sys/build.rs:103: Binaries already built, using existing...
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraCommon.h:79:9: error: unknown type name 'uintptr_t', err: true
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraCommon.h:84:9: error: unknown type name 'uint32_t', err: true
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraCommon.h:85:9: error: unknown type name 'int64_t', err: true
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:932:18: error: unknown type name 'uint32_t', err: true
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:933:17: error: unknown type name 'int64_t', err: true
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:934:15: error: unknown type name 'int64_t', err: true
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:935:19: error: unknown type name 'int64_t', err: true
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:948:14: error: unknown type name 'int64_t', err: true
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:949:15: error: unknown type name 'int64_t', err: true
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:950:15: error: unknown type name 'int64_t', err: true
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:962:14: error: unknown type name 'int64_t', err: true
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:963:15: error: unknown type name 'int64_t', err: true
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:978:14: error: unknown type name 'int64_t', err: true
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:979:14: error: unknown type name 'int64_t', err: true
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:981:15: error: unknown type name 'int64_t', err: true
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:997:18: error: unknown type name 'int64_t', err: true
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:998:18: error: unknown type name 'int64_t', err: true
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:1014:19: error: unknown type name 'int64_t', err: true
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraCore.h:248:20: error: unknown type name 'uint16_t', err: true
fatal error: too many errors emitted, stopping now [-ferror-limit=], err: true

--- stderr
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraCommon.h:79:9: error: unknown type name 'uintptr_t'
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraCommon.h:84:9: error: unknown type name 'uint32_t'
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraCommon.h:85:9: error: unknown type name 'int64_t'
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:932:18: error: unknown type name 'uint32_t'
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:933:17: error: unknown type name 'int64_t'
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:934:15: error: unknown type name 'int64_t'
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:935:19: error: unknown type name 'int64_t'
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:948:14: error: unknown type name 'int64_t'
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:949:15: error: unknown type name 'int64_t'
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:950:15: error: unknown type name 'int64_t'
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:962:14: error: unknown type name 'int64_t'
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:963:15: error: unknown type name 'int64_t'
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:978:14: error: unknown type name 'int64_t'
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:979:14: error: unknown type name 'int64_t'
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:981:15: error: unknown type name 'int64_t'
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:997:18: error: unknown type name 'int64_t'
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:998:18: error: unknown type name 'int64_t'
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraDebug.h:1014:19: error: unknown type name 'int64_t'
/Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-sys-0.2.2/target/source-1.5.1/lib/Jsrt/ChakraCore.h:248:20: error: unknown type name 'uint16_t'
fatal error: too many errors emitted, stopping now [-ferror-limit=]
thread 'main' panicked at 'Failed to generate binding: ()', src/libcore/result.rs:860
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by darfink** [comment]
What XCode version are you using? Seems `cstdint` is missing.

I notice now that I haven't listed XCode >= 7 as a requirement on macOS.

**Comment by corbinu** [comment]
It is 8.3.3 :/

**Comment by corbinu** [comment]
Looks like reinstalling the commandline tools fixed it. Maybe only there were out of date. Thanks!

**Comment by corbinu** [comment]
Now I get this 

```
Compiling chakracore v0.1.0
error[E0425]: cannot find function `JsCreatePropertyIdUtf8` in this scope
  --> /Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-0.1.0/src/property.rs:21:23
   |
21 |             jsassert!(JsCreatePropertyIdUtf8(bytes.as_ptr() as _, bytes.len(), &mut reference));
   |                       ^^^^^^^^^^^^^^^^^^^^^^ did you mean `JsCreatePropertyId`?

error[E0425]: cannot find value `JsCopyPropertyIdUtf8` in this scope
  --> /Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-0.1.0/src/property.rs:33:47
   |
33 |         ::util::to_string_impl(self.as_raw(), JsCopyPropertyIdUtf8).unwrap()
   |                                               ^^^^^^^^^^^^^^^^^^^^ did you mean `JsCopyPropertyId`?

error[E0433]: failed to resolve. Use of undeclared type or module `ffi`
  --> /Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-0.1.0/src/runtime.rs:32:9
   |
32 |         ffi::initialize();
   |         ^^^^^^^^^^^^^^^ Use of undeclared type or module `ffi`

error[E0425]: cannot find function `JsCreateStringUtf8` in this scope
  --> /Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-0.1.0/src/value/string.rs:14:23
   |
14 |             jsassert!(JsCreateStringUtf8(string.as_ptr(), string.len(), &mut value));
   |                       ^^^^^^^^^^^^^^^^^^ did you mean `JsCreateStringUtf16`?

error[E0425]: cannot find value `JsCopyStringUtf8` in this scope
  --> /Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-0.1.0/src/value/string.rs:33:47
   |
33 |         ::util::to_string_impl(self.as_raw(), JsCopyStringUtf8).unwrap()
   |                                               ^^^^^^^^^^^^^^^^ did you mean `JsCopyStringUtf16`?

error[E0308]: mismatched types
  --> /Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-0.1.0/src/value/function.rs:38:35
   |
38 |             JsCreateFunction(Some(Self::callback), context, reference)
   |                                   ^^^^^^^^^^^^^^ expected struct `chakracore_sys::JsRef`, found *-ptr
   |
   = note: expected type `unsafe extern "system" fn(chakracore_sys::JsRef, bool, *mut chakracore_sys::JsRef, u16, *mut libc::c_void) -> chakracore_sys::JsRef`
              found type `unsafe extern "system" fn(chakracore_sys::JsRef, bool, *mut chakracore_sys::JsRef, u16, *mut libc::c_void) -> *mut libc::c_void {value::function::Function::callback}`

error[E0308]: mismatched types
  --> /Users/corbinu/.cargo/registry/src/github.com-1ecc6299db9ec823/chakracore-0.1.0/src/value/function.rs:46:55
   |
46 |             JsCreateNamedFunction(name.as_raw(), Some(Self::callback), context, reference)
   |                                                       ^^^^^^^^^^^^^^ expected struct `chakracore_sys::JsRef`, found *-ptr
   |
   = note: expected type `unsafe extern "system" fn(chakracore_sys::JsRef, bool, *mut chakracore_sys::JsRef, u16, *mut libc::c_void) -> chakracore_sys::JsRef`
              found type `unsafe extern "system" fn(chakracore_sys::JsRef, bool, *mut chakracore_sys::JsRef, u16, *mut libc::c_void) -> *mut libc::c_void {value::function::Function::callback}`

error: aborting due to previous error(s)

error: Could not compile `chakracore`.
```

**Comment by corbinu** [comment]
Looks like compiling against master branch here works fine

**Comment by darfink** [comment]
Yeah, unfortunately build errors were introduced in chakracore 1.0 due to the chakracore-sys changes, albeit the most recent crates version (2.0), works without issues.

**Comment by corbinu** [comment]
Ahh ok sorry I just copied and pasted 1.0 from the README. Is a great project am super excited to see somebody working on this! I am really excited about the idea of that some of my Rust apps could allow for easy dynamic plugins in JS. Think it will really help drive adoption if the users don't have to learn Rust.

**Comment by darfink** [comment]
Thanks for mentioning! I just updated the README's version.

Glad to hear! It was similar reasons I started this project in the first place :)
